In [2]:
x1, x2 = eval(input('입력(콤마로 구분하여 입력하시오):'))
b = 2
out = 1 if x1 + x2 >= b else 0
print('뉴런 출력:', out)

입력(콤마로 구분하여 입력하시오):0, 1
뉴런 출력: 0


In [3]:
x1, x2 = eval(input('입력(콤마로 구분하여 입력하시오):'))
b = -0.5
w1 = 0.38
w2 = 0.42
y = x1*w1 + x2*w2 +b
out = 1 if y >= 0.0 else 0
print('뉴런 출력:', out)

입력(콤마로 구분하여 입력하시오):0, 1
뉴런 출력: 0


In [4]:
import numpy as np
#AND
x1, x2 = eval(input('입력(콤마로 구분하여 입력하시오):'))
X = np.array([x1, x2])
b = -0.5
w1 = 0.38
w2 = 0.42
W = np.array([w1, w2]).reshape(-1, 1)

y = np.dot(X,W) + b

out = 1 if y >= 0.0 else 0

print('뉴런 출력:', out)

입력(콤마로 구분하여 입력하시오):1,1
뉴런 출력: 1


In [5]:
# OR
X = np.array([[0,0],
             [0,1],
             [1,0],
             [1,1]])
b = -0.01
w1 = 0.36
w2 = 0.39
W = np.array([w1, w2]).reshape(-1, 1)

y = np.dot(X,W) + b

print("y:\n", y, y.shape)

out = np.zeros((X.shape[0], 1))
out = (y>=0.0).astype(int)

print('out:\n', out)

out = (y>=0.0).astype(float)
print('out:\n', out)


y:
 [[-0.01]
 [ 0.38]
 [ 0.35]
 [ 0.74]] (4, 1)
out:
 [[0]
 [1]
 [1]
 [1]]
out:
 [[0.]
 [1.]
 [1.]
 [1.]]


In [6]:
X = np.array([[0,0],
             [0,1],
             [1,0],
             [1,1]])
t = np.array([0.,1.,1.,1.]).reshape(-1,1) # target
b = -0.01
w1 = 0.36
w2 = 0.39
W = np.array([w1, w2]).reshape(-1, 1)

y = np.dot(X,W) + b

print("y:\n", y, y.shape)

out = np.zeros((X.shape[0], 1))
out = (y>=0.0).astype(int)

print('out:\n', out)

out = np.zeros((X.shape[0], 1))
out = (y>=0.0).astype(float)
print('out:\n', out)

e = t-y
print("error:\n", e)

d_w = np.zeros_like(W)
d_w[0]= e[0][0]*X[0][0] + e[1][0]*X[1][0] + e[2][0]*X[2][0] + e[3][0]*X[3][0]
d_w[1]= e[0][0]*X[0][1] + e[1][0]*X[1][1] + e[2][0]*X[2][1] + e[3][0]*X[3][1]

print('d_w:\n',d_w)

d_w2 = np.dot(X.T, e)
print('d_w2:\n', d_w2)

y:
 [[-0.01]
 [ 0.38]
 [ 0.35]
 [ 0.74]] (4, 1)
out:
 [[0]
 [1]
 [1]
 [1]]
out:
 [[0.]
 [1.]
 [1.]
 [1.]]
error:
 [[0.01]
 [0.62]
 [0.65]
 [0.26]]
d_w:
 [[0.91]
 [0.88]]
d_w2:
 [[0.91]
 [0.88]]


In [ ]:
import random

def step_f(x):
  

In [17]:
import numpy as np
def stepfunc(x):

    return (x>=0.0).astype(float)

In [9]:
import random

In [18]:
class Perceptron:
    def __init__(self,x,y):
        self.input = x
        self.w = np.random.rand(self.input.shape[1],1)
        self.t = y
        self.output = np.zeros_like(self.t)
    
    def feedforward(self):
        self.output = stepfunc(np.dot(self.input, self.w))
    
    def train(self, eta):
        d_w = np.dot(self.input.T, eta*(self.t - self.output))
        # update the weights
        self.w += d_w

In [19]:
# 논리-AND를 수행하는 퍼셉트론 ,
# the third input is for bias
X = np.array([[0,0, 1],
              [0,1, 1],
              [1,0, 1],
              [1,1, 1]])
y = np.array([[0],[0],[0],[1]])
nn = Perceptron(X, y)

for i in range(1500):
    nn.feedforward()
    nn.train(0.01)
    
print('output:\n',nn.output)
print('weight:\n', nn.w)

output:
 [[0.]
 [0.]
 [0.]
 [1.]]
weight:
 [[ 0.15516439]
 [ 0.2345094 ]
 [-0.2535627 ]]


In [20]:
# or 연산
X = np.array([[0,0, 1],
              [0,1, 1],
              [1,0, 1],
              [1,1, 1]])
y = np.array([[0],[1],[1],[1]])
nn = Perceptron(X, y)

for i in range(1500):
    nn.feedforward()
    nn.train(0.01)
    
print('output:\n',nn.output)
print('weight:\n', nn.w)

output:
 [[0.]
 [1.]
 [1.]
 [1.]]
weight:
 [[ 0.06503023]
 [ 0.97395538]
 [-0.00224781]]


In [31]:
# Xor
X = np.array([[0,0, 1],
              [0,1, 1],
              [1,0, 1],
              [1,1, 1]])
y = np.array([[0],[1],[1],[0]])
nn = Perceptron(X, y)

for i in range(1500):
    nn.feedforward()
    nn.train(0.01)
    
print('output:\n',nn.output)
print('weight:\n', nn.w)

output:
 [[1.]
 [1.]
 [1.]
 [1.]]
weight:
 [[ 0.00262165]
 [-0.01075353]
 [-0.01707063]]


In [32]:
def sigmoid(x):
    return 1.0/(1+np.exp(-x))



In [33]:
def sigmoid_derivative(x):
    return x * (1.0 - x)

In [36]:
class NeuralNetwork:
    def __init__(self, x, y):
        self.input = x 
        self.w1 =  np.random.rand(self.input.shape[1],4)
        self.w2 =  np.random.rand(4,1) 
        self.t =  y
        self.output =  np.zeros_like(self.t)
        
    def feedforward(self):
        self.h1 =  sigmoid(np.dot(self.input, self.w1))
        self.output =  sigmoid(np.dot(self.h1, self.w2))

    def backprop(self):
        e1 = (self.t - self.output) * sigmoid_derivative(self.output)
        d_w2 = np.dot(self.h1.T, e1)
        e2 = np.dot(e1, self.w2.T) * sigmoid_derivative(self.h1)
        d_w1 = np.dot(self.input.T, e2)
        
        self.w1 += d_w1
        self.w2 += d_w2

In [37]:
# 논리-XOR 연산 MLP
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
y = np.array([[0],[1],[1],[0]])
nn = NeuralNetwork(X,y)

for i in range(1500):
    nn.feedforward()
    nn.backprop()


print("Output:\n", nn.output)
print("Wgt in_h1:\n",nn.w1)
print("Wgt hd_Out:\n",nn.w2)

Output:
 [[0.0208739 ]
 [0.95507952]
 [0.95129649]
 [0.05722175]]
Wgt in_h1:
 [[-1.40449446  5.52199055  6.44637102  1.69891762]
 [ 5.83495955  5.04357354 -4.43132946  1.31269382]
 [-1.11987799 -1.18023493  1.73705393  1.40239687]]
Wgt hd_Out:
 [[-6.85676779]
 [ 8.43194701]
 [-6.91844153]
 [ 2.16737746]]


In [38]:
# 논리-OR 연산 MLP
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
y = np.array([[0],[1],[1],[1]])
nn = NeuralNetwork(X,y)

for i in range(1500):
    nn.feedforward()
    nn.backprop()


print("Output:\n", nn.output)
print("Wgt in_h1:\n",nn.w1)
print("Wgt hd_Out:\n",nn.w2)

Output:
 [[0.0274273 ]
 [0.98654523]
 [0.98639691]
 [0.99971257]]
Wgt in_h1:
 [[ 2.44202378  1.66493563 -2.10062341  3.64638702]
 [ 2.22676172  2.23095461 -2.08541207  3.53502462]
 [-1.55148982 -1.35917168  1.70356181 -2.10934668]]
Wgt hd_Out:
 [[ 2.3862335 ]
 [ 1.72065202]
 [-5.73449594]
 [ 4.74695637]]


In [39]:
# 논리-AND 연산 MLP
X = np.array([[0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1]])
y = np.array([[0],[0],[0],[1]])
nn = NeuralNetwork(X,y)

for i in range(1500):
    nn.feedforward()
    nn.backprop()


print("Output:\n", nn.output)
print("Wgt in_h1:\n",nn.w1)
print("Wgt hd_Out:\n",nn.w2)

Output:
 [[2.82508032e-04]
 [1.83748844e-02]
 [1.92057066e-02]
 [9.73201819e-01]]
Wgt in_h1:
 [[ 2.07067352 -2.90040736  1.36540747 -1.36996306]
 [ 1.01365259 -3.13182779  1.86923323 -1.5008842 ]
 [-1.65280918  4.23499404 -1.89006426  1.80195029]]
Wgt hd_Out:
 [[ 3.20579687]
 [-6.99998839]
 [ 3.35839415]
 [-2.59581217]]
