# Gradient Descent

In [1]:
import torch
import torch.nn.functional as F

In [2]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [4]:
x = torch.rand_like(target)
# This means the final scalar will be differentiate by x.
x.requires_grad = True
# You can get gradient of x, after differentiation.

x

tensor([[0.9479, 0.4407, 0.3199],
        [0.9015, 0.1389, 0.5245],
        [0.4168, 0.5548, 0.1999]], requires_grad=True)

In [5]:
loss = F.mse_loss(x, target)

loss

tensor(0.1995, grad_fn=<MseLossBackward0>)

In [6]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    
    loss.backward() # Calculate gradients.

    x = x - learning_rate * x.grad
    
    # You don't need to aware this now.
    x.detach_() 
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 1.2068e-01
tensor([[0.7595, 0.3872, 0.3155],
        [0.7900, 0.2191, 0.5413],
        [0.4797, 0.6093, 0.3555]], requires_grad=True)
2-th Loss: 7.3006e-02
tensor([[0.6130, 0.3456, 0.3120],
        [0.7033, 0.2815, 0.5543],
        [0.5287, 0.6517, 0.4765]], requires_grad=True)
3-th Loss: 4.4164e-02
tensor([[0.4990, 0.3133, 0.3094],
        [0.6359, 0.3301, 0.5645],
        [0.5667, 0.6846, 0.5706]], requires_grad=True)
4-th Loss: 2.6717e-02
tensor([[0.4103, 0.2881, 0.3073],
        [0.5835, 0.3678, 0.5724],
        [0.5964, 0.7103, 0.6438]], requires_grad=True)
5-th Loss: 1.6162e-02
tensor([[0.3413, 0.2685, 0.3057],
        [0.5427, 0.3972, 0.5785],
        [0.6194, 0.7302, 0.7007]], requires_grad=True)
6-th Loss: 9.7769e-03
tensor([[0.2877, 0.2533, 0.3044],
        [0.5110, 0.4201, 0.5833],
        [0.6373, 0.7457, 0.7450]], requires_grad=True)
7-th Loss: 5.9144e-03
tensor([[0.2460, 0.2414, 0.3034],
        [0.4863, 0.4378, 0.5870],
        [0.6512, 0.7578, 0.7795]], requi

- |target| = (3,3)
- |x| = (3,3)
- L(x) = MSE(x, target)