# Linear Layer

In [1]:
import torch

## Raw Linear Layer

$$\begin{gathered}
y=x\cdot{W}+b, \\
\text{where }x\in\mathbb{R}^{N\times{n}}\text{, }y\in\mathbb{R}^{N\times{m}}. \\
\\
\text{Thus, }W\in\mathbb{R}^{n\times{m}}\text{ and }b\in\mathbb{R}^m.
\end{gathered}$$

In [2]:
W = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]])
b = torch.FloatTensor([2, 2])

In [3]:
print(W.size())
print(b.size())

torch.Size([3, 2])
torch.Size([2])


In [4]:
def linear(x, W, b):
    y = torch.matmul(x, W) + b
    
    return y

In [5]:
x = torch.FloatTensor([[1, 1, 1],
                       [2, 2, 2],
                       [3, 3, 3],
                       [4, 4, 4]])

print(x.size())

torch.Size([4, 3])


In [6]:
y = linear(x, W, b)

In [7]:
print(y.size())

torch.Size([4, 2])


## nn.Module

In [8]:
import torch.nn as nn

In [9]:
class MyLinear(nn.Module):

    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)

    # You should override 'forward' method to implement detail.
    # The input arguments and outputs can be designed as you wish.
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = torch.matmul(x, self.W) + self.b
        # |y| = (batch_size, input_dim) * (input_dim, output_dim)
        #     = (batch_size, output_dim)
        
        return y

In [10]:
linear = MyLinear(3, 2)

y = linear(x)

In [11]:
print(y.size())

torch.Size([4, 2])


In [12]:
for p in linear.parameters():
    print(p)

You can see that there is no weight parameters to learn.
Above way can forward(or calculate) values, but it cannot be trained.

### Correct way: nn.Parameter

In [13]:
class MyLinear(nn.Module):

    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))
        
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = torch.matmul(x, self.W) + self.b
        # |y| = (batch_size, input_dim) * (input_dim, output_dim)
        #     = (batch_size, output_dim)
        
        return y

-  nn.Parameter로 감싸야 nn.Module을 상속받은 MyLinear 객체에 제대로 등록이 됨

Reference: https://pytorch.org/docs/stable/nn.html#torch.nn.Parameter

A kind of Tensor that is to be considered a module parameter.

Parameters are Tensor subclasses, that have a very special property when used with Module s - when they’re assigned as Module attributes they are automatically added to the list of its parameters, and will appear e.g. in parameters() iterator. Assigning a Tensor doesn’t have such effect. This is because one might want to cache some temporary state, like last hidden state of the RNN, in the model. If there was no such class as Parameter, these temporaries would get registered too.

In [14]:
linear = MyLinear(3, 2)

y = linear(x)

In [15]:
print(y.size())

torch.Size([4, 2])


In [16]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[2.2325e-35, 0.0000e+00],
        [3.3631e-44, 0.0000e+00],
        [       nan, 1.0800e+02]], requires_grad=True)
Parameter containing:
tensor([2.2324e-35, 0.0000e+00], requires_grad=True)


## nn.Linear

In [17]:
linear = nn.Linear(3, 2)

y = linear(x)

In [18]:
print(y.size())

torch.Size([4, 2])


In [19]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[ 0.0641,  0.4558,  0.0175],
        [-0.3228, -0.0536,  0.3064]], requires_grad=True)
Parameter containing:
tensor([-0.3808,  0.0172], requires_grad=True)


### nn.Module can contain other nn.Module's child classes.

In [20]:
class MyLinear(nn.Module):

    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()
        
        self.linear = nn.Linear(input_dim, output_dim)
        
    def forward(self, x):
        # |x| = (batch_size, input_dim)
        y = self.linear(x)
        # |y| = (batch_size, output_dim)
        
        return y

In [21]:
linear = MyLinear(3, 2)

y = linear(x)

In [22]:
print(y.size())

torch.Size([4, 2])


In [23]:
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[-0.0687, -0.4856, -0.3070],
        [-0.4090,  0.0245, -0.5656]], requires_grad=True)
Parameter containing:
tensor([0.5747, 0.4093], requires_grad=True)
