# PyTorch Tensor

In [ ]:
import torch

## Tensor Allocation

In [ ]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
lt

tensor([[1, 2],
        [3, 4]])

In [ ]:
bt = torch.ByteTensor([[1, 0],
                       [0, 1]])
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [ ]:
x = torch.FloatTensor(3, 2)
x

tensor([[0.0000e+00, 4.6566e-10],
        [0.0000e+00, 4.6566e-10],
        [9.8091e-45, 0.0000e+00]])

## NumPy Compatibility

In [ ]:
import numpy as np

# Define numpy array.
x = np.array([[1, 2],
              [3, 4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [ ]:
x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [ ]:
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


## Tensor Type-casting

In [ ]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [ ]:
lt.float()

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
torch.FloatTensor([1, 0]).byte()

tensor([1, 0], dtype=torch.uint8)

## Get Shape

In [ ]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

Get tensor shape.

In [ ]:
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


Get number of dimensions in the tensor.

In [ ]:
print(x.dim())
print(len(x.size()))

3
3


Get number of elements in certain dimension of the tensor.

In [ ]:
print(x.size(1))
print(x.shape[1])

2
2


Get number of elements in the last dimension.

In [ ]:
print(x.size(-1))
print(x.shape[-1])

2
2
