# How to use GPU

In [1]:
import torch
import torch.nn as nn

## Convert to CUDA tensor: cuda()

- tensor를 gpu에서 선언하는 방법

In [2]:
x = torch.cuda.FloatTensor(2, 2)

x

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

- tensor를 cpu에서 gpu로 보내는 방법

In [3]:
x = torch.FloatTensor(2, 2)

x

tensor([[3.4820e+31, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])

In [4]:
x.cuda()

tensor([[3.4820e+31, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]], device='cuda:0')

- device 지정

In [5]:
d = torch.device('cuda:0')

In [6]:
# cuda로 호출하는 경우는 move가 아닌 copy
x.cuda(device=d)

tensor([[3.4820e+31, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]], device='cuda:0')

In [7]:
x.device

device(type='cpu')

## Convert to CUDA tensor: to()

In [8]:
x.to(device=d)

tensor([[3.4820e+31, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]], device='cuda:0')

## Convert to CPU tensor from CUDA tensor

In [9]:
x = torch.cuda.FloatTensor(2, 2)

In [10]:
x = x.cpu()

In [11]:
d = torch.device('cpu')
x = x.to(d)

## Move model from CPU to GPU.

In [12]:
def print_params(model):
    for p in model.parameters():
        print(p)

- p = next(model.parameters(1))
     - model의 맨 첫 번째 parameter가 p에 assign 됨
        - 그 후 p.device로 model이 대충 어느 device에 있는지 앎
          (model 안에 parameter들이 같은 device 안에 있다는 가정)

In [13]:
linear = nn.Linear(2, 2)

print_params(linear)

Parameter containing:
tensor([[ 0.4143, -0.5855],
        [-0.5144,  0.0764]], requires_grad=True)
Parameter containing:
tensor([-0.3370,  0.6216], requires_grad=True)


In [14]:
linear = linear.cuda()

print_params(linear)

Parameter containing:
tensor([[ 0.4143, -0.5855],
        [-0.5144,  0.0764]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.3370,  0.6216], device='cuda:0', requires_grad=True)


In [15]:
linear = linear.cpu()

print_params(linear)

Parameter containing:
tensor([[ 0.4143, -0.5855],
        [-0.5144,  0.0764]], requires_grad=True)
Parameter containing:
tensor([-0.3370,  0.6216], requires_grad=True)


In [16]:
d = torch.device('cuda:0')
linear = linear.to(d)

print_params(linear)

Parameter containing:
tensor([[ 0.4143, -0.5855],
        [-0.5144,  0.0764]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.3370,  0.6216], device='cuda:0', requires_grad=True)


Note that nn.Module class does not have 'device' property.

In [17]:
linear.device

AttributeError: ignored

## Tricks

In [18]:
x = torch.cuda.FloatTensor(2, 2)

In [19]:
# x와 같은 타입이면서 같은 device에 있는 어떤 특정 사이즈의 tensor를 만듬
x.new(2, 2)

tensor([[-3.6893e+19,  1.6685e+00],
        [ 5.1444e-01,  7.6368e-02]], device='cuda:0')

In [20]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [21]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [22]:
list(linear.parameters())[0].new(2, 2)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')